connect to sample;
CREATE SCHEMA "DVDEMO";
set current schema="DVDEMO";

CREATE TABLE ACCOUNTS
  (
  CUSTID INT NOT NULL,
  TX_COUNT INT NOT NULL,
  BALANCE DEC(9,2) NOT NULL
  );

CREATE TABLE CUSTOMERS
  (
        CUSTID INT NOT NULL,
        FIRST_NAME VARCHAR(20) ,
        LAST_NAME VARCHAR(20) ,
        STATE CHAR(2),
        ZIPCODE CHAR(5)
  );

CREATE TABLE CUSTOMERS_JSON
  (
  INFO VARCHAR(1000) NOT NULL,
  CUSTID GENERATED ALWAYS AS (JSON_VALUE(INFO,'$.customerid' RETURNING INT))
  );


CREATE TABLE STOCK_HISTORY
  (
  SYMBOL  VARCHAR(4) NOT NULL,
  TX_DATE CHAR(10) NOT NULL,
  HIGH    DEC(9,2) NOT NULL,
  LOW     DEC(9,2) NOT NULL,
  OPEN    DEC(9,2) NOT NULL,
  CLOSE   DEC(9,2) NOT NULL,
  VOLUME  INT NOT NULL
);


CREATE TABLE STOCK_SYMBOLS
  (
  SYMBOL  VARCHAR(4) NOT NULL,
  COMPANY VARCHAR(64) NOT NULL
  );


CREATE TABLE STOCK_TRANSACTIONS (
   TX_NO   INT NOT NULL,
   TX_DATE CHAR(10) NOT NULL,
   CUSTID INT NOT NULL,
   SYMBOL  VARCHAR(4) NOT NULL,
   PRICE   DEC(9,2) NOT NULL,
   QUANTITY INT NOT NULL
); 
